# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000
batch_size_ssl: 128

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "macl_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

num_heads: 1
attn_dim: 16
softTemperature: 1
isSoftmax: False

consensus_dim: 4
consensus_loss_weight: 1
hidden_state_loss_weight: 1
reward_loss_weight: 1
# tau: 0.996
tau_start: 0.05
tau_finish: 0.99
tau_anneal_time: 50000
center_tau: 1.0
# online_temp: 0.1
# target_temp: 0.04
online_temp: 1.0
target_temp: 1.0


mac: "macl_mac"
agent: "macl"

name: "macl"