env: foraging

env_args:
  map_name: 'lbf'
  field_size: 10
  players: 4
  max_food: 4
  force_coop: True
  partially_observe: True
  sight: 2
  is_print: False
  need_render: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2050000
test_interval: 10000
test_nepisode: 32
